#!/usr/bin/env python3
import sys
if count(sys.argv) > 1:
    try :
        for i in sys.argv[1:]:
           m = i.split(':')
           n = int(m[0])
           a = int(m[1])
    except ValueError:
        print('Parameter Error')
    shb = a*0.165
    b = a*0.835-3500
    c = 0
    if b > 0 and b <= 1500:
        c = 0.03*b
    elif b > 1500 and b <=4500:
        c = 0.1*b-105
    elif b > 4500 and b <= 9000:
        c = 0.2*b-555
    elif b > 9000 and b <= 35000:
        c = 0.25*b-1005
    elif b > 35000 and b <= 55000:
        c = 0.3**b-2755
    elif b > 55000 and b <= 80000:
        c = 0.35*b-5505
    elif b > 80000:
        c = 0.45*b-13505
    d = a-shb-c
    print(n+':'+d,'.2f','.2f')
else :
    print('Parameter Error')
~                 
