#!/usr/bin/env python3
import sys
if len(sys.argv) != 7:
    print('Parameter Error')
else :
    try:
        in = sys.argv[1:]
        c = in.index('-c')
        cfg = in[c+1]
        d = in.index('-d')
        usr = in[d+1]
        o = in.index('-o')
        slr = in[o+1]
    except ValueError :
        print('Parameter Error')
    dic = {}
    #dicu = {}
    c = 0
    try :
        with open('cfg') as f:
            for i in f:
                kv = i.strip().split('=')
                k = kv[0]
                v = kv[1]
                dic[k] = v
    except FileNotFoundError,ValueError :
        print('File Not Found')
   try:
        ks = int(dic[Yanglao]+dic[YiLiao]+dic[ShiYe]+dic[GongShang]+dic[Shengyu]+dic[GongJiJin])                    
    except :
        print('wrong')
   try :
        with open('usr') as u:
            for i in u:
                kv1 = i.strip(',')
                k1 = kv1[0]
                v1 = kv1[1]
                #dicu[k1] = v1
                if v1 < JiShuL:
                    shb = v1*ks
                elif v1 >= JiShuL and v1 < JiShuH:
                    shb = v1*ks
                elif v1 >= JiShuH:
                    shb = JiShuH*ks
                b = v1-shb-3500
                if b > 0 and b <= 1500:
                    c = 0.03*b
                elif b > 1500 and b <=4500:
                    c = 0.1*b-105
                elif b > 4500 and b <= 9000:
                    c = 0.2*b-555
                elif b > 9000 and b <= 35000:
                    c = 0.25*b-1005
                elif b > 35000 and b <= 55000:
                    c = 0.3**b-2755
                elif b > 55000 and b <= 80000:
                    c = 0.35*b-5505
                elif b > 80000:
                    c = 0.45*b-13505
                #file = '/tmp/gongzi.csv'
                sj = v1-shb-c
                with open(slr,'w') as fl:
                    fl.write(str(k1)+','+str(v1)+','+str(format(shb,'.2f'))+','+str(format(c,'.2f'))+','+str(format(sj,'.2f')))
    except FileNotFoundError,ValueError :
        print('File Not Found')                                                                            
    
    
