#!/usr/bin/env python3
import sys
if len(sys.argv) != 7:
    print('Parameter Error')
else :
    in = sys.argv[1:]
    c = in.index('-c')
    cfg = in[c+1]
    d = in.index('-d')
    usr = in[d+1]
    o = in.index('-o')
    slr = in[o+1]
    dic = {}
    try :
        with open('cfg') as f:
            for i in f:
                kv = i.strip().split('=')
                k = kv[0]
                v = kv[1]
                dic[k] = v
    except FileNotFoundError :
        print('File Not Found')
~                                                                               
                         
    
